version: "3"

services:

  frontend:
    restart: always
    container_name: frontend-electronic-queue
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - common

  backend:
    restart: always
    container_name: backend-electronic-queue
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    networks:
      - common

networks:
  common:
    driver: bridge
